version: '3'
services:

## Router
  router01:
    image: mongo
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27117:27017
    volumes:
      - router1:/data/db
  # router02:
  #   image: mongo
  #   container_name: router-02
  #   command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
  #   volumes:
  #     - ./scripts:/scripts
  #   ports:
  #     - 27118:27017
  #   links:
  #     - router01

## Config Servers
  configsvr01:
    image: mongo
    container_name: mongo-config-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - cfg1:/data/db
    ports:
      - 27119:27017
    links:
      - shard01-a
      - shard02-a
      # - shard03-a
  configsvr02:
    image: mongo
    container_name: mongo-config-02 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - cfg2:/data/db
    ports:
      - 27120:27017
    links:
      - configsvr01
  configsvr03:
    image: mongo
    container_name: mongo-config-03 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
       - cfg3:/data/db
    ports:
      - 27121:27017
    links:
      - configsvr02

## Shards
  ## Shards 01
   
  shard01-a:
    image: mongo
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - shard1svr1:/data/db
    ports:
      - 27122:27017
    links:
      - shard01-b
      - shard01-c
  shard01-b:
    image: mongo
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
    - shard1svr2:/data/db
    ports:
      - 27123:27017
  shard01-c:
    image: mongo
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - shard1svr3:/data/db
    ports:
      - 27124:27017

  ## Shards 02
  shard02-a:
    image: mongo
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
     - shard2svr1:/data/db
    ports:
      - 27125:27017
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    image: mongo
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - shard2svr2:/data/db
    ports:
      - 27126:27017
  shard02-c:
    image: mongo
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - shard2svr3:/data/db
    ports:
      - 27127:27017

  # ## Shards 03
  # shard03-a:
  #   image: mongo
  #   container_name: shard-03-node-a
  #   command: mongod --port 27017 --shardsvr --replSet rs-shard-03
  #   volumes:
  #     - shard3svr1:/data/db
  #   ports:
  #     - 27128:27017
  #   links:
  #     - shard03-b
  #     - shard03-c
  # shard03-b:
  #   image: mongo
  #   container_name: shard-03-node-b
  #   command: mongod --port 27017 --shardsvr --replSet rs-shard-03
  #   volumes:
  #      - shard3svr2:/data/db
  #   ports:
  #     - 27129:27017
  # shard03-c:
  #   image: mongo
  #   container_name: shard-03-node-c
  #   command: mongod --port 27017 --shardsvr --replSet rs-shard-03
  #   volumes:
  #     - shard3svr3:/data/db
  #   ports:
  #     - 27130:27017

volumes:
  cfg1: {}
  cfg2: {}
  cfg3: {}
  router1: {}
  shard1svr1: {}
  shard1svr2: {}
  shard1svr3: {}
  shard2svr1: {}
  shard2svr2: {}
  shard2svr3: {}
  # shard3svr1: {}
  # shard3svr2: {}
  # shard3svr3: {}